export const LOAD_EVENTO_REQUEST = 'LOAD_EVENTO_REQUEST';
export const LOAD_EVENTO_REQUEST_SUCCESS = 'LOAD_EVENTO_REQUEST_SUCCESS';
export const LOAD_EVENTO_REQUEST_ERROR = 'LOAD_EVENTO_REQUEST_ERROR';
